### ISSUE TITLE
Consider using vectors in Expression

### ISSUE THREAD

**Issue by ArashPartow** [piotrek13k/betterKMeans#1]
ExprTk supports vectors as variables. It would definitely be more efficient to create a single 1D vector instead of multiple variables for each element of Eigen::VectorXd parameters.

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L1648

**Comment by kroolp** [comment]
@ArashPartow I am grateful for your time for analyzing my code. At the moment I'm working on math side of my project. I'll consider your proposition after that.

Thanks for advise.

**Comment by ArashPartow** [comment]
cool, if you have any issues let me know.
